
#define EXTRA_FEATURES STD_OFF

#define DEV_ERROR_DETECT STD_ON
#define UART_ERROR_DETECT STD_OFF

#define TASKS_NB 9
#define MAX_NB_STATES 5
#define CONTEXT_SWITCH_CAPABILITY STD_OFF

#define MODULES_USING_INTERRUPT 5

#define PORT_TOTAL_NB 5

#define DIO_CONFIGURED_CHANNLES 9

#define MAX_NB_ADC_CHANNELS 3
#define MAX_NB_ADC_GROUPS 1

#define ADC_SAMPLES_NB 5

#define ADC_DEINIT_API STD_ON
#define ADC_SETUP_BUFF_API STD_ON
#define ADC_READ_GP_CAPABILITY STD_ON
#define ADC_ENABLE_START_STOP_GROUP_API STD_ON
#define ADC_GRP_NOTIF_CAPABILITY STD_ON
#define ADC_GET_STATUS_API STD_ON

#define I2C_DEINIT_API STD_ON
#define I2C_GET_STATUS_API STD_ON

#define GPT_DEINIT_API STD_ON
#define GPT_GET_STATUS_API STD_ON

#define PWM_DEINIT_API STD_ON
#define PWM_GET_STATUS_API STD_ON

#define UART_DEINIT_API STD_ON
#define UART_GET_STATUS_API STD_ON

#define EEP_DEINIT_API STD_ON
#define EEP_ERASE_API STD_ON
#define EEP_COMPARE_API STD_ON
#define EEP_GET_STATUS_API STD_ON

#define DISPLAY_INNER_DELAY 50   //ms
